//
//  BeerListView.Action+feature.swift
//  Beers
//
//  Created Christian Elies on 23.04.21.
//  Copyright © 2021 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

extension BeerListView.Action {
    var feature: BeerListAction {
        switch self {
        case BeerListView.Action.onAppear:
            return BeerListAction.onAppear
        case let BeerListView.Action.selectBeer(beer):
            return BeerListAction.selectBeer(beer: beer)
        case let BeerListView.Action.move(indexSet, toOffset):
            return BeerListAction.move(indexSet: indexSet, toOffset: toOffset)
        case let BeerListView.Action.delete(indexSet):
            return BeerListAction.delete(indexSet: indexSet)
        case BeerListView.Action.refresh:
            return BeerListAction.refresh
        }
    }
}
