//
//  BeerListRowFeature.swift
//  Beers
//
//  Created Christian Elies on 23.04.21.
//  Copyright © 2021 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

import ComposableArchitecture

struct BeerListRowFeature: ReducerProtocol {
    struct State: Equatable {
        let beer: Beer
    }

    enum Action: Equatable {
        case onAppear
        case delete
    }

    func reduce(into state: inout State, action: Action) -> EffectTask<Action> {
        return .none
    }
}

extension BeerListRowFeature.State: Identifiable {
    var id: Int { beer.id }
}
