//
//  BeerListRowView.Action+feature.swift
//  Beers
//
//  Created Christian Elies on 23.04.21.
//  Copyright © 2021 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

extension BeerListRowView.Action {
    var feature: BeerListRowAction {
        switch self {
            case BeerListRowView.Action.onAppear:
                return BeerListRowAction.onAppear
            case let BeerListRowView.Action.didTapRow(id):
                return BeerListRowAction.didTapRow(id: id)
        }
    }
}
