//
//  AppEnvironment.swift
//  Beers
//
//  Created Christian Elies on 24.04.21.
//  Copyright © 2021 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

import ComposableArchitecture

struct AppEnvironment {
    var fetchBeers: () -> Effect<[Beer], BeerListError>
    var nextBeers: () -> Effect<BeersResult, BeerListError>
    var fetchBeer: (_ id: Int) -> Effect<Beer, BeerListRowError>
}
