//
//  BeerDetailView.swift
//  Beers
//
//  Created Christian Elies on 24.04.21.
//  Copyright © 2021 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

import ComposableArchitecture
import SwiftUI

struct BeerDetailView: View {
    let store: Store<BeerDetailState, BeerDetailAction>

    var body: some View {
        WithViewStore(
            store.scope(
                state: { $0.view },
                action: { (viewAction: BeerDetailView.Action) in
                    viewAction.feature
                }
            )
        ) { viewStore in
            VStack {
                if let beer = viewStore.beer {
                    BeerView(
                        beer: beer
                    )
                }
            }
            .onAppear {
                viewStore.send(.onAppear)
            }
        }
    }
}
