//
//  BeerDetailView.swift
//  Beers
//
//  Created Christian Elies on 24.04.21.
//  Copyright © 2021 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

import ComposableArchitecture
import SwiftUI

struct BeerDetailView: View {
    let store: StoreOf<BeerDetailFeature>

    var body: some View {
        WithViewStore(
            store.scope(
                state: \.view,
                action: { (viewAction: BeerDetailView.Action) in
                    viewAction.feature
                }
            ),
            observe: { $0 }
        ) { viewStore in
            VStack {
                if let beer = viewStore.beer {
                    BeerView(beer: beer)
                }
            }
            .onAppear {
                viewStore.send(.onAppear)
            }
        }
    }
}
