//
//  BeerListRowReducer.swift
//  Beers
//
//  Created Christian Elies on 23.04.21.
//  Copyright © 2021 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

import ComposableArchitecture

enum BeerListRowModule {}

extension BeerListRowModule {
    static var reducer: Reducer<BeerListRowState, BeerListRowAction, BeerListRowEnvironment> {
        .init { state, action, environment in
            return .none
        }
    }
}
