//
//  AppAction.swift
//  Beers
//
//  Created Christian Elies on 24.04.21.
//  Copyright © 2021 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

enum AppAction: Equatable {
    case onAppear
    case beerList(BeerListAction)
}
