//
//  AppView.Action+feature.swift
//  Beers
//
//  Created Christian Elies on 24.04.21.
//  Copyright © 2021 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

extension AppView.Action {
    var feature: AppAction {
        switch self {
            case AppView.Action.onAppear:
                return AppAction.onAppear
        }
    }
}
