//
//  BeerListView.Action+feature.swift
//  Beers
//
//  Created Christian Elies on 23.04.21.
//  Copyright © 2021 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

extension BeerListView.Action {
    var feature: BeerListFeature.Action {
        switch self {
        case .onAppear:
            return .onAppear
        case let .selectBeer(beer):
            return .selectBeer(beer: beer)
        case let .setBeerPresented(isPresented):
            return .setBeerPresented(isPresented: isPresented)
        case let .move(indexSet, toOffset):
            return .move(indexSet: indexSet, toOffset: toOffset)
        case let .delete(indexSet):
            return .delete(indexSet: indexSet)
        case .refresh:
            return .refresh
        }
    }
}
