//
//  BeerListAction.swift
//  Beers
//
//  Created Christian Elies on 23.04.21.
//  Copyright © 2021 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

enum BeerListAction: Equatable {
    case onAppear
    case row(index: Int, action: BeerListRowAction)
    case fetchBeersResponse(Result<[Beer], BeerListError>)
    case selectBeer(beer: Beer?)
}
