//
//  BeerListView+Action.swift
//  Beers
//
//  Created Christian Elies on 23.04.21.
//  Copyright © 2021 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

import Foundation

extension BeerListView {
    enum Action: Equatable {
        case onAppear
        case move(indexSet: IndexSet, toOffset: Int)
        case delete(indexSet: IndexSet)
        case refresh
    }
}
