//
//  BeerListEnvironment.swift
//  Beers
//
//  Created Christian Elies on 23.04.21.
//  Copyright © 2021 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

import ComposableArchitecture
import Foundation

struct BeerListEnvironment {
    var mainQueue: () -> AnySchedulerOf<DispatchQueue>
    var fetchBeers: () -> Effect<[Beer], BeerListError>
    var nextBeers: () -> Effect<BeersResult, BeerListError>
    var fetchBeer: (_ id: Int) -> Effect<Beer, BeerError>
    var moveBeer: (_ fromOffsets: IndexSet, _ toOffset: Int) -> Effect<Void, BeerListError>
    var deleteBeer: (_ indexSet: IndexSet) -> Effect<Void, BeerListError>
    var deleteBeerWithID: (Int) -> Effect<Void, BeerListError>
}
