//
//  BeerListReducer.swift
//  Beers
//
//  Created Christian Elies on 23.04.21.
//  Copyright © 2021 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

import Combine
import ComposableArchitecture

enum BeerListModule {}

extension BeerListModule {
    static var reducer: Reducer<BeerListState, BeerListAction, BeerListEnvironment> {
        Reducer.combine(
            BeerListRowModule.reducer
                .forEach(
                    state: \.rowStates,
                    action: /BeerListAction.row(index:action:),
                    environment: { listEnvironment in
                        BeerListRowEnvironment(fetchBeer: listEnvironment.fetchBeer)
                    }
                )
            ,
            Reducer<BeerListState, BeerListAction, BeerListEnvironment> { state, action, environment in
                switch action {
                case .onAppear:
                    guard state.page == 0 else {
                        return .none
                    }
                    return .init(value: .fetchBeers)
                case let .fetchBeersResponse(.success(result)):
                    state.page = result.page
                    let rowStates = result.beers.map { beer in
                        BeerListRowState(beer: beer)
                    }
                    state.rowStates = rowStates
                    state.viewState = .loaded(rowStates)
                    return .none
                case let .fetchBeersResponse(.failure(error)):
                    state.viewState = .failed(error)
                    return .none
                case let .row(index, rowAction):
                    switch rowAction {
                    case .onAppear:
                        guard state.viewState != .loading else {
                            return .none
                        }

                        guard index == state.rowStates.endIndex - 1 else {
                            return .none
                        }

                        return environment.nextBeers()
                            .catchToEffect()
                            .map(BeerListAction.fetchBeersResponse)
                    case let .didTapRow(id: .some(id)):
                        state.selection = state.rowStates.first(where: { $0.id == id})?.beer
                        return .none
                    default:
                        return .none
                    }
                case let .selectBeer(beer):
                    state.selection = beer
                    return .none
                case let .move(indexSet, toOffset):
                    state.rowStates.move(fromOffsets: indexSet, toOffset: toOffset)
                    return environment.moveBeer(indexSet, toOffset)
                        .fireAndForget()
                case let .delete(indexSet):
                    indexSet.forEach { state.rowStates.remove(at: $0) }
                    return environment.deleteBeer(indexSet)
                        .fireAndForget()
                case .fetchBeers:
                    return environment.fetchBeers()
                        .map { BeersResult(beers: $0, page: 1) }
                        .catchToEffect()
                        .map(BeerListAction.fetchBeersResponse)
                case .refresh:
                    return .init(value: .fetchBeers)
                }
            }
        )
    }
}
