name: iOS workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Test
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        run: |
          bundle install
      - name: Test
        run: |
          bundle exec fastlane scan --scheme "Beers (iOS)"
